name: supply_task
description: "補給任務"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
