name: supply_task
description: "補給任務"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  url_launcher: ^6.3.0
  intl: ^0.19.0
  url_strategy: ^0.2.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.0
  firebase_remote_config: ^5.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

